"""Emit the cross-model BLADE-G removal results as a LaTeX booktabs table (a compact
alternative to figures/blade_s3_crossmodel_wide). Reuses the exact DATA that the figure
plots (same operating points), so table and figure never diverge.

Cell = behavior metric pi: base -> pruned, plus WikiText Delta-ppl at that point.
Refusal target = 0 (keyword refusal rate); A/B target = 0.5 (chance). "--" = not exhibited
(baseline bias < 0.10 of chance, skipped). dagger = below the 0.10 exhibited-gate, gate-bypassed.
Output: docs/blade_s3_table.tex
"""
import runpy
from pathlib import Path

d = runpy.run_path("scripts/plot_s3_crossmodel_wide.py")
DATA, ORDER, TAGS = d["DATA"], d["ORDER"], d["TAGS"]
MODELS = list(TAGS.keys())

PRETTY = {"refusal": "Refusal", "power-seeking": "Power-seeking",
          "wealth-seeking": "Wealth-seeking", "deception": "Deception",
          "corrigibility": "Corrigibility", "self-awareness": "Self-awareness",
          "self-rate-highly": "Self-rate-highly", "sycophancy": "Sycophancy"}


def rate1(x):  # behavior rate as a 1-decimal percentage number (unit % lives in the header)
    return f"{x * 100:.1f}"


def cell(c):
    status, base, pruned = c[0], c[1], c[2]
    if status != "ok" or pruned is None:
        return "\\multicolumn{4}{c}{\\textendash}"        # base / pruned / prune / ppl
    ppl, sel = c[3], c[4]                                  # e.g. '+1.5%' / '0.016%'
    ppl = ppl.replace("†", "").replace("%", "")           # sign + 1 decimal, % moved to header
    sel = sel.replace("%", "")                             # pruning rate keeps its own precision
    return f"{rate1(base)} & {rate1(pruned)} & {sel} & {ppl}"


def main():
    ncol = "l" + "".join(" rrrr" for _ in MODELS)
    head1 = " & " + " & ".join("\\multicolumn{4}{c}{%s\\,(\\%%)}" % m for m in MODELS) + " \\\\"
    cmid = " ".join(f"\\cmidrule(lr){{{2+4*i}-{5+4*i}}}" for i in range(len(MODELS)))
    head2 = "Behavior & " + " & ".join("base & prun. & $\\rho$ & $\\Delta$ppl" for _ in MODELS) + " \\\\"

    lines = [
        "% Auto-generated by scripts/make_s3_table.py -- do not edit by hand.",
        "\\begin{table*}[t]", "\\centering", "\\scriptsize",
        "\\setlength{\\tabcolsep}{3pt}",
        f"\\begin{{tabular}}{{{ncol}}}", "\\toprule",
        head1, cmid, head2, "\\midrule",
    ]
    for b in ORDER:
        row = PRETTY[b] + " & " + " & ".join(cell(DATA[b][m]) for m in MODELS) + " \\\\"
        lines.append(row)
        if b == "refusal":
            lines.append("\\midrule")
    lines += [
        "\\bottomrule", "\\end{tabular}",
        "\\caption{Cross-model behavior removal with BLADE (all columns in \\%). \\emph{base} and "
        "\\emph{prun.} are the behavior rate before and after pruning (lower is more removed), "
        "$\\rho$ the fraction of residual-writer weights zeroed, and $\\Delta$ppl the WikiText "
        "perplexity change. Behavior rate is the refusal rate for Refusal (target $0$) and the A/B "
        "pick-rate otherwise (chance $50$). \\textendash: not exhibited.}",
        "\\label{tab:s3-crossmodel}", "\\end{table*}",
    ]
    out = Path("docs/blade_s3_table.tex")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
